ci: add shellcheck

diff --git a/script/update-action-readme b/script/update-action-readme
--- a/script/update-action-readme
+++ b/script/update-action-readme
@@ -2,15 +2,15 @@
 
 set -e
 
-for i in $*; do
-  # ignore if the file does not end with /action.yaml
-  if [[ "$i" != *"/action.yaml" ]]; then
-    echo "skipping: ${i}"
-    continue
-  fi
+for i in "$@"; do
+	# ignore if the file does not end with /action.yaml
+	if [[ "$i" != *"/action.yaml" ]]; then
+		echo "skipping: ${i}"
+		continue
+	fi
 
-  echo "npx action-docs --no-banner -s "${i}""
-  cd $(dirname "$i")
-  npx action-docs@2 --no-banner -s action.yaml -u README.md || echo "action-docs failed for $i"
-  cd -
+	echo "npx action-docs --no-banner -s ${i}"
+	cd "$(dirname "$i")"
+	npx action-docs@2 --no-banner -s action.yaml -u README.md || echo "action-docs failed for $i"
+	cd -
 done
